In [285]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder

In [286]:
root_path = '/Users/silvianac/Downloads/DMC_2017_task/'
items_data = pd.read_csv(root_path + 'items.csv', sep='|')
train_data = pd.read_csv(root_path + 'train.csv', sep='|')
class_data = pd.read_csv(root_path + 'class.csv', sep='|')

In [287]:
train_pids = train_data.pid.unique()
test_pids = class_data.pid.unique()

In [288]:
class_data

          lineID  day    pid  adFlag  availability  competitorPrice  price
0              1   93   4772       0             1            11.54  12.04
1              2   93  11548       0             2             6.84   8.60
2              3   93   1958       0             1             9.67  10.39
3              4   93  15071       0             2            17.37  16.45
4              5   93   2117       0             1             4.94   5.45
5              6   93  21129       0             1             8.78   6.55
6              7   93   8977       0             1             2.64   2.15
7              8   93   5654       0             1            13.16  13.14
8              9   93   3274       1             1            11.78  10.95
9             10   93  15423       0             1            10.88  10.95
10            11   93  17770       0             1             2.53   2.70
11            12   93  20331       0             1             5.16   8.06
12            13   93  20376       0             1            11.76  12.52
13            14   93  13913       1             1            13.96  15.35
14            15   93   8347       1             1             1.31   1.32
15            16   93  13939       0             1            90.19  38.45
16            17   93  21218       0             1             7.05   9.85
17            18   93  16640       1             1            12.74  14.25
18            19   93  11246       0             1             4.31   5.70
19            20   93     15       0             1            17.33  20.77
20            21   93  10041       1             1            14.03  14.25
21            22   93  13646       0             1            18.14  22.15
22            23   93  15767       0             1            22.41  18.64
23            24   93   8736       0             1            73.69  38.45
24            25   93   2803       1             1             1.64   1.38
25            26   93   1950       1             1             6.81   5.45
26            27   93   9332       1             1             8.35   9.85
27            28   93   6178       1             1            14.28  16.45
28            29   93  14064       0             1            13.74  16.39
29            30   93   6626       0             1            17.57  20.86
...          ...  ...    ...     ...           ...              ...    ...
1210737  1210738  123   3254       0             1             1.30   1.30
1210738  1210739  123  21021       0             1             5.90   9.90
1210739  1210740  123   2655       1             1            13.73  15.35
1210740  1210741  123   5664       0             1            12.64  15.36
1210741  1210742  123  14218       1             1             2.19   2.15
1210742  1210743  123  15927       1             1             4.26   4.35
1210743  1210744  123   5626       0             1             2.17   2.70
1210744  1210745  123   2492       1             1             1.58   1.32
1210745  1210746  123   4082       0             2            22.18  26.33
1210746  1210747  123  14253       0             2              NaN   8.25
1210747  1210748  123  16593       1             1            21.97  24.14
1210748  1210749  123   7427       0             1             5.93   6.55
1210749  1210750  123  11714       0             1             3.42   4.35
1210750  1210751  123  14761       0             2             5.32   5.92
1210751  1210752  123  20620       0             1             7.83  10.95
1210752  1210753  123   5654       0             1            16.53  13.14
1210753  1210754  123   1097       0             1            26.73  29.59
1210754  1210755  123   1426       1             1             6.57   7.65
1210755  1210756  123  19208       0             1            23.09  29.05
1210756  1210757  123   8744       0             1             8.57   6.55
1210757  1210758  123   9528       0             1             9.33   9.29
1210758  1210759  123   2655       1             1            13.73  15.35
1210759  1210760  123   4838       1             1             2.73   3.03
1210760  1210761  123   9214       0             1             1.58   1.45
1210761  1210762  123  10765       0             1            12.52  15.36
1210762  1210763  123  11241       1             1             9.78   9.85
1210763  1210764  123   4900       1             1            13.19  14.25
1210764  1210765  123  20837       0             1             7.13   9.85
1210765  1210766  123   3850       1             1             3.52   4.90
1210766  1210767  123   5664       0             1            12.75  15.36

[1210767 rows x 7 columns]

In [289]:
train_pids.shape

(21928,)

In [290]:
test_pids.shape

(20525,)

In [291]:
unknown_pids = np.setdiff1d(test_pids, train_pids)

In [292]:
unknown_pids.shape

(100,)

In [293]:
unknown_pids

array([  331,   999,  1093,  1402,  1480,  1534,  1923,  2329,  2330,
        2965,  3763,  4097,  4325,  4426,  4516,  4660,  5168,  5272,
        5503,  5785,  5882,  6093,  6216,  6287,  6339,  6398,  6466,
        6485,  6556,  6742,  7253,  7289,  7290,  7323,  7507,  8091,
        8596,  8681,  8768,  9143,  9149,  9602,  9780,  9803,  9882,
        9889,  9939, 10133, 10195, 10222, 10226, 10852, 11234, 11439,
       11465, 11946, 12262, 12335, 12492, 12722, 13516, 13536, 13543,
       13857, 14588, 14839, 14864, 15085, 15192, 16288, 16579, 16710,
       16737, 16945, 17273, 17457, 17564, 17654, 17844, 18010, 18207,
       18211, 18434, 18645, 18671, 18673, 19102, 19543, 19625, 19689,
       19747, 20082, 20311, 21295, 21517, 21616, 21705, 21847, 21923, 21943])

In [294]:
items_data

,pid,manufacturer,group,content,unit,pharmForm,genericProduct,salesIndex,category,campaignIndex,rrp
0,1,1,2FOI,80,ST,TAB,0,40,NaN,NaN,10.89
1,2,1,2FOI,80,ST,Tab,0,40,NaN,NaN,10.89
2,3,1,2FOI,10,G,GLO,0,40,NaN,NaN,16.45
3,4,1,2FOI,80,ST,TAB,0,40,NaN,NaN,10.89
4,5,2,10OJ03JS,8,ST,PUL,0,40,1.0,NaN,22.53
5,6,1,2FOI,10,G,GLO,0,40,2.0,NaN,9.85
6,7,3,21OKG,15,ST,TRA,0,53,3.0,NaN,21.45
7,8,1,2FOI,80,ST,TAB,0,40,2.0,NaN,10.89
8,9,1,2FOI,10,G,GLO,0,40,NaN,NaN,9.85
9,10,4,12OS2F,30,ST,FTA,0,40,4.0,A,21.99
10,11,4,12OS2F,60,ST,FTA,0,40,4.0,A,38.49
11,12,5,10OZ12OI,14,ST,KMR,1,40,5.0,NaN,9.85
12,13,6,22OI3,30,ML,CRE,0,53,6.0,NaN,15.29
13,14,7,14OI03OI,7,ST,VSU,0,53,7.0,NaN,13.72
14,15,7,14OI03OI,14,ST,VSU,0,53,7.0,NaN,21.86
15,16,2,10OJ03JS,8,ST,PUL,0,40,1.0,NaN,22.53
16,17,8,22OI3,75,ML,CRE,0,53,8.0,NaN,14.25
17,18,9,22OI9,30,ML,AEO,0,53,9.0,NaN,8.69
18,19,9,22OI3,10,ML,EMU,0,53,10.0,NaN,9.90
19,20,9,22OI3,10,ML,EMU,0,53,10.0,NaN,9.90
20,21,9,22OI3,10,ML,EMU,0,53,10.0,NaN,9.90
21,22,9,22OI9,100,ML,KON,0,53,NaN,NaN,15.40
22,23,10,10OS0F,20,ML,TRO,0,52,11.0,NaN,6.33
23,24,11,20OI0,1,ST,KOM,0,53,12.0,NaN,0.78
24,25,12,22OI3,250,ML,GEL,0,53,4.0,NaN,6.55
25,26,13,2EOZ,15,ST,TUE,0,53,NaN,NaN,2.62
26,27,11,20OI3,1,ST,PFL,0,53,NaN,NaN,3.61
27,28,11,20OI3,1,ST,PFL,0,53,12.0,NaN,1.54
28,29,11,20OI3,1,ST,PFL,0,53,12.0,NaN,2.18
29,30,11,20OI3,1,ST,PFL,0,53,NaN,NaN,0.34
...,...,...,...,...,...,...,...,...,...,...,...
22005,22006,668,22OIK,500,G,BAD,0,53,71.0,NaN,10.89
22006,22007,373,1COS21OJ,100,ML,Lse,1,40,NaN,NaN,4.39
22007,22008,86,21OIG,30,ST,Kap,0,53,3.0,NaN,38.23
22008,22009,225,22OI3,75,ML,SAL,0,53,NaN,NaN,14.29
22009,22010,475,21OKG,180,ST,KAP,0,53,3.0,NaN,39.49
22010,22011,363,2G,12,G,GLO,0,52,409.0,NaN,8.91
22011,22012,363,2G,12,G,GLO,0,52,409.0,NaN,8.91
22012,22013,363,2G,12,G,GLO,0,52,289.0,NaN,8.91
22013,22014,363,2G,12,G,GLO,0,52,409.0,NaN,8.91
22014,22015,363,2G,12,G,GLO,0,52,409.0,NaN,8.91
22015,22016,363,2G,12,G,GLO,0,52,409.0,NaN,8.91
22016,22017,363,2G,12,G,GLO,0,52,409.0,NaN,8.91
22017,22018,363,2G,12,G,GLO,0,52,409.0,NaN,8.91
22018,22019,363,2G,12,G,GLO,0,52,289.0,NaN,8.91
22019,22020,363,2G,12,G,GLO,0,52,409.0,NaN,8.91
22020,22021,363,2G,12,G,GLO,0,52,289.0,NaN,8.91
22021,22022,363,2G,12,G,GLO,0,52,289.0,NaN,8.91
22022,22023,363,2G,12,G,GLO,0,52,289.0,NaN,8.91
22023,22024,387,22OI2,150,ML,NaN,0,53,24.0,NaN,7.65
22024,22025,387,22OI2,12,ML,XGM,0,53,6.0,NaN,2.20
22025,22026,387,22OI3,12,ML,XGM,0,53,135.0,NaN,2.20
22026,22027,1018,21OKG,500,G,NaN,0,53,323.0,NaN,9.79
22027,22028,329,22OI3,200,ML,LOT,0,53,95.0,NaN,7.87
22028,22029,41,22OI2,400,ML,XDG,0,53,NaN,NaN,16.39
22029,22030,994,21OKG,30,ST,KAP,0,53,343.0,NaN,21.95
22030,22031,844,21OIG,100,ST,Tab,0,53,NaN,NaN,13.42
22031,22032,387,22OI3,475,ML,NaN,0,53,8.0,NaN,5.45
22032,22033,19,22OI3,100,G,SAL,0,53,NaN,NaN,6.60
22033,22034,79,22OIO,1,ST,NaN,0,53,NaN,NaN,27.49
22034,22035,256,21OKG,120,ST,Wka,0,53,NaN,NaN,47.96

In [295]:
items_data['campaignIndex'].dtype.kind

'O'

In [296]:
items_data_ext = items_data.apply(lambda x: x.fillna(0) if x.dtype.kind in ['b', 'i', 'u', 'f', 'c'] else x.fillna('UNK'))

In [297]:
items_data_ext

,pid,manufacturer,group,content,unit,pharmForm,genericProduct,salesIndex,category,campaignIndex,rrp
0,1,1,2FOI,80,ST,TAB,0,40,0.0,UNK,10.89
1,2,1,2FOI,80,ST,Tab,0,40,0.0,UNK,10.89
2,3,1,2FOI,10,G,GLO,0,40,0.0,UNK,16.45
3,4,1,2FOI,80,ST,TAB,0,40,0.0,UNK,10.89
4,5,2,10OJ03JS,8,ST,PUL,0,40,1.0,UNK,22.53
5,6,1,2FOI,10,G,GLO,0,40,2.0,UNK,9.85
6,7,3,21OKG,15,ST,TRA,0,53,3.0,UNK,21.45
7,8,1,2FOI,80,ST,TAB,0,40,2.0,UNK,10.89
8,9,1,2FOI,10,G,GLO,0,40,0.0,UNK,9.85
9,10,4,12OS2F,30,ST,FTA,0,40,4.0,A,21.99
10,11,4,12OS2F,60,ST,FTA,0,40,4.0,A,38.49
11,12,5,10OZ12OI,14,ST,KMR,1,40,5.0,UNK,9.85
12,13,6,22OI3,30,ML,CRE,0,53,6.0,UNK,15.29
13,14,7,14OI03OI,7,ST,VSU,0,53,7.0,UNK,13.72
14,15,7,14OI03OI,14,ST,VSU,0,53,7.0,UNK,21.86
15,16,2,10OJ03JS,8,ST,PUL,0,40,1.0,UNK,22.53
16,17,8,22OI3,75,ML,CRE,0,53,8.0,UNK,14.25
17,18,9,22OI9,30,ML,AEO,0,53,9.0,UNK,8.69
18,19,9,22OI3,10,ML,EMU,0,53,10.0,UNK,9.90
19,20,9,22OI3,10,ML,EMU,0,53,10.0,UNK,9.90
20,21,9,22OI3,10,ML,EMU,0,53,10.0,UNK,9.90
21,22,9,22OI9,100,ML,KON,0,53,0.0,UNK,15.40
22,23,10,10OS0F,20,ML,TRO,0,52,11.0,UNK,6.33
23,24,11,20OI0,1,ST,KOM,0,53,12.0,UNK,0.78
24,25,12,22OI3,250,ML,GEL,0,53,4.0,UNK,6.55
25,26,13,2EOZ,15,ST,TUE,0,53,0.0,UNK,2.62
26,27,11,20OI3,1,ST,PFL,0,53,0.0,UNK,3.61
27,28,11,20OI3,1,ST,PFL,0,53,12.0,UNK,1.54
28,29,11,20OI3,1,ST,PFL,0,53,12.0,UNK,2.18
29,30,11,20OI3,1,ST,PFL,0,53,0.0,UNK,0.34
...,...,...,...,...,...,...,...,...,...,...,...
22005,22006,668,22OIK,500,G,BAD,0,53,71.0,UNK,10.89
22006,22007,373,1COS21OJ,100,ML,Lse,1,40,0.0,UNK,4.39
22007,22008,86,21OIG,30,ST,Kap,0,53,3.0,UNK,38.23
22008,22009,225,22OI3,75,ML,SAL,0,53,0.0,UNK,14.29
22009,22010,475,21OKG,180,ST,KAP,0,53,3.0,UNK,39.49
22010,22011,363,2G,12,G,GLO,0,52,409.0,UNK,8.91
22011,22012,363,2G,12,G,GLO,0,52,409.0,UNK,8.91
22012,22013,363,2G,12,G,GLO,0,52,289.0,UNK,8.91
22013,22014,363,2G,12,G,GLO,0,52,409.0,UNK,8.91
22014,22015,363,2G,12,G,GLO,0,52,409.0,UNK,8.91
22015,22016,363,2G,12,G,GLO,0,52,409.0,UNK,8.91
22016,22017,363,2G,12,G,GLO,0,52,409.0,UNK,8.91
22017,22018,363,2G,12,G,GLO,0,52,409.0,UNK,8.91
22018,22019,363,2G,12,G,GLO,0,52,289.0,UNK,8.91
22019,22020,363,2G,12,G,GLO,0,52,409.0,UNK,8.91
22020,22021,363,2G,12,G,GLO,0,52,289.0,UNK,8.91
22021,22022,363,2G,12,G,GLO,0,52,289.0,UNK,8.91
22022,22023,363,2G,12,G,GLO,0,52,289.0,UNK,8.91
22023,22024,387,22OI2,150,ML,UNK,0,53,24.0,UNK,7.65
22024,22025,387,22OI2,12,ML,XGM,0,53,6.0,UNK,2.20
22025,22026,387,22OI3,12,ML,XGM,0,53,135.0,UNK,2.20
22026,22027,1018,21OKG,500,G,UNK,0,53,323.0,UNK,9.79
22027,22028,329,22OI3,200,ML,LOT,0,53,95.0,UNK,7.87
22028,22029,41,22OI2,400,ML,XDG,0,53,0.0,UNK,16.39
22029,22030,994,21OKG,30,ST,KAP,0,53,343.0,UNK,21.95
22030,22031,844,21OIG,100,ST,Tab,0,53,0.0,UNK,13.42
22031,22032,387,22OI3,475,ML,UNK,0,53,8.0,UNK,5.45
22032,22033,19,22OI3,100,G,SAL,0,53,0.0,UNK,6.60
22033,22034,79,22OIO,1,ST,UNK,0,53,0.0,UNK,27.49
22034,22035,256,21OKG,120,ST,Wka,0,53,0.0,UNK,47.96

In [299]:
from collections import defaultdict
from sklearn.preprocessing import LabelEncoder

encodings_dict = defaultdict(LabelEncoder)
features_to_encode = ['manufacturer', 'group', 'content', 'pharmForm', 'unit', 'genericProduct', 'category', 'campaignIndex']

# Encoding the variables
items_data_ext = items_data_ext.apply(lambda x: encodings_dict[x.name].fit_transform(x) if x.name in features_to_encode else x)

In [300]:
items_data_ext.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22035 entries, 0 to 22034
Data columns (total 11 columns):
pid               22035 non-null int64
manufacturer      22035 non-null int64
group             22035 non-null int64
content           22035 non-null int64
unit              22035 non-null int64
pharmForm         22035 non-null int64
genericProduct    22035 non-null int64
salesIndex        22035 non-null int64
category          22035 non-null int64
campaignIndex     22035 non-null int64
rrp               22035 non-null float64
dtypes: float64(1), int64(10)
memory usage: 1.8 MB

In [200]:
enc = OneHotEncoder(categorical_features=[1, 2, 3, 4, 5, 6, 8, 9], sparse=False)

In [301]:
items_data_ext = enc.fit_transform(items_data_ext)

In [302]:
items_data_ext.shape

(22035, 2854)

In [303]:
# non-OHE cols: 20851 - PID, 20852 - salesIndex, 20853 - RRP
for i in range(10):
 print(items_data_ext[i][2851])

1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0

In [322]:
# create a matrix with all the features (except pids) for the unseen items and one for the seen items
unknown_pids.sort()
train_pids.sort()

unknown_matr = np.zeros((unknown_pids.shape[0], items_data_ext.shape[1] - 1))
train_matr = np.zeros((train_pids.shape[0], items_data_ext.shape[1] - 1))

for pid, i in zip(unknown_pids, range(len(unknowm_pids))):
    unknown_matr[i] = np.concatenate((items_data_ext[unknown_pids[i] - 1][:2851], items_data_ext[unknown_pids[i] - 1][2852:2854]))

for pid, i in zip(train_pids, range(len(train_pids))):
    train_matr[i] = np.concatenate((items_data_ext[train_pids[i] - 1][:2851], items_data_ext[train_pids[i] - 1][2852:2854]))
    
print(unknown_matr.shape)
print(train_matr.shape)
print(unknown_matr[0][:])
print(train_matr[0][:])

(100, 2853)
(21928, 2853)
[  0.     0.     0.   ...,   1.    53.     1.36]
[  1.     0.     0.   ...,   1.    40.    10.89]

In [323]:
# compute the cosine similarity between the unseen matrix and train matrix.
from sklearn.metrics.pairwise import cosine_similarity

similarity = cosine_similarity(unknown_matr, train_matr)

In [324]:
similarity.shape

(100, 21928)

In [341]:
output = np.zeros((similarity.shape[0], 3))

identical = 0
above_99 = 0

for i in range(100):
    if similarity[i][:].max() == 1:
        identical += 1
    else:
        if similarity[i][:].max() >= 0.99:
            above_99 += 1
    output[i][0] = unknown_pids[i]
    output[i][1] = train_pids[similarity[i][:].argmax()]
    output[i][2] = similarity[i][:].max()

print('Identical: %d' % identical)
print('Similarity above 0.99: %d' % above_99)

output_df = pd.DataFrame(output, columns=['unseen_pid', 'train_pid', 'similarity'])
output_df[['unseen_pid', 'train_pid']] = output_df[['unseen_pid', 'train_pid']].astype(int)

Identical: 25
Similarity above 0.99: 75

In [342]:
output_df

    unseen_pid  train_pid  similarity
0          331        330    0.999642
1          999       6077    0.999283
2         1093      14206    0.999641
3         1402        686    0.999671
4         1480       8017    0.999917
5         1534        334    0.999291
6         1923       7915    0.999036
7         2329       2323    0.999399
8         2330       2327    1.000000
9         2965        216    1.000000
10        3763       9748    0.999318
11        4097       4098    1.000000
12        4325       4285    1.000000
13        4426      19417    0.999284
14        4516      10725    0.999427
15        4660       4659    0.999554
16        5168       9544    0.999624
17        5272       4286    1.000000
18        5503       6075    0.999319
19        5785      11001    1.000000
20        5882      12449    0.999736
21        6093      10605    0.999680
22        6216       6199    0.999995
23        6287       5756    0.999988
24        6339       5179    1.000000
25        6398       6380    1.000000
26        6466       4933    0.999566
27        6485        239    1.000000
28        6556       6557    1.000000
29        6742       4286    1.000000
..         ...        ...         ...
70       16579       7990    0.999337
71       16710      18874    0.999244
72       16737      16738    1.000000
73       16945      14009    0.999001
74       17273      17274    0.999409
75       17457      17456    1.000000
76       17564      17563    0.999729
77       17654      17655    0.999430
78       17844      19322    0.999282
79       18010       3372    0.999809
80       18207      18204    1.000000
81       18211      18204    1.000000
82       18434      12104    0.999061
83       18645       7608    0.999744
84       18671      18677    1.000000
85       18673      18670    1.000000
86       19102      16437    0.998949
87       19543       3229    0.998233
88       19625      20944    0.999767
89       19689      10276    0.999658
90       19747      15202    0.999291
91       20082       5741    0.998996
92       20311      20120    0.999205
93       21295      13133    0.999373
94       21517      21234    0.999763
95       21616        951    0.999165
96       21705      21703    1.000000
97       21847      12721    0.998700
98       21923      10547    0.999247
99       21943      21619    1.000000

[100 rows x 3 columns]

In [326]:
items_data[items_data['pid'] == 331]

,pid,manufacturer,group,content,unit,pharmForm,genericProduct,salesIndex,category,campaignIndex,rrp
330,331,135,20OI2,1,ST,BIN,0,53,104.0,NaN,1.36

In [327]:
items_data[items_data['pid'] == 330]

,pid,manufacturer,group,content,unit,pharmForm,genericProduct,salesIndex,category,campaignIndex,rrp
329,330,135,20OI2,1,ST,BIN,0,53,NaN,NaN,1.23

In [328]:
items_data[items_data['pid'] == 2330]

,pid,manufacturer,group,content,unit,pharmForm,genericProduct,salesIndex,category,campaignIndex,rrp
2329,2330,433,2FOI,10,G,GLO,0,40,200.0,NaN,7.56

In [329]:
items_data[items_data['pid'] == 2327]

,pid,manufacturer,group,content,unit,pharmForm,genericProduct,salesIndex,category,campaignIndex,rrp
2326,2327,433,2FOI,10,G,GLO,0,40,200.0,NaN,7.56

In [381]:
pd.DataFrame.to_csv??

In [388]:
output_df.to_csv('./unseen_pids_similarities.csv', sep='|', index=False)

In [362]:
# check the similarity on train_pids only, as we might actually discover very similar products
train_similarity = cosine_similarity(train_matr)

In [375]:
training_similarities_df = pd.DataFrame(columns=['pid', 'top_similarities', 'avg_similarity'])
for i in range(len(train_similarity)):
    similarities = train_similarity[i][:]
    args = similarities.argsort()[::-1]
    top_similar_products = []
    for j in args[:20]:
        top_similar_products.append((train_pids[j], similarities[j]))
    similarity_mean = similarities.mean()
    training_similarities_df.loc[i] = [train_pids[i], top_similar_products, similarity_mean]

In [376]:
training_similarities_df

,pid,top_similarities,avg_similarity
0,1.0,"[(1, 1.0), (4606, 1.0), (4311, 1.0), (5234, 1....",0.968510
1,2.0,"[(15003, 1.0), (14831, 1.0), (6341, 1.0), (634...",0.968465
2,3.0,"[(7240, 1.0), (3, 1.0), (7025, 1.0), (7158, 1....",0.967126
3,4.0,"[(1, 1.0), (4606, 1.0), (4311, 1.0), (5234, 1....",0.968510
4,5.0,"[(16, 1.0), (5, 1.0), (13620, 0.998488847765),...",0.951137
5,6.0,"[(9994, 1.0), (9995, 1.0), (5259, 1.0), (7251,...",0.966814
6,7.0,"[(7, 1.0), (18193, 0.999082309802), (11125, 0....",0.968025
7,8.0,"[(4394, 1.0), (5214, 1.0), (5186, 1.0), (2661,...",0.968421
8,9.0,"[(4599, 1.0), (9815, 1.0), (15484, 1.0), (9822...",0.966904
9,10.0,"[(10, 1.0), (19198, 0.998584460343), (12444, 0...",0.952656
10,11.0,"[(11, 1.0), (1303, 0.998882044724), (2546, 0.9...",0.873464
11,12.0,"[(12, 1.0), (12111, 0.999413497476), (13461, 0...",0.966331
12,13.0,"[(13, 1.0), (18501, 0.999552590275), (17758, 0...",0.969624
13,14.0,"[(14, 1.0), (20376, 0.99962074221), (13779, 0....",0.968263
14,15.0,"[(15, 1.0), (20906, 0.999087588344), (4099, 0....",0.967544
15,16.0,"[(16, 1.0), (5, 1.0), (13620, 0.998488847765),...",0.951137
16,17.0,"[(17, 1.0), (10231, 0.999414975577), (11486, 0...",0.968822
17,18.0,"[(18, 1.0), (10501, 0.999308560461), (5160, 0....",0.958699
18,19.0,"[(21, 1.0), (20, 1.0), (19, 1.0), (18386, 0.99...",0.961799
19,20.0,"[(21, 1.0), (20, 1.0), (19, 1.0), (18386, 0.99...",0.961799
20,21.0,"[(21, 1.0), (20, 1.0), (19, 1.0), (18386, 0.99...",0.961799
21,22.0,"[(22, 1.0), (3085, 0.999309268866), (39, 0.999...",0.969738
22,23.0,"[(23, 1.0), (5926, 0.999273274009), (15860, 0....",0.951715
23,24.0,"[(24, 1.0), (7648, 0.999992175086), (21341, 0....",0.926412
24,25.0,"[(25, 1.0), (7621, 0.999606803877), (891, 0.99...",0.952092
25,26.0,"[(26, 1.0), (12472, 0.999193110844), (10865, 0...",0.935885
26,27.0,"[(27, 1.0), (9519, 0.999646475362), (8902, 0.9...",0.940513
27,28.0,"[(28, 1.0), (29, 0.999927479411), (21346, 0.99...",0.930450
28,29.0,"[(29, 1.0), (28, 0.999927479411), (21346, 0.99...",0.933695
29,30.0,"[(30, 1.0), (20736, 0.99964359381), (21346, 0....",0.924065
...,...,...,...
21898,22006.0,"[(22006, 1.0), (12377, 0.998977699537), (10853...",0.963830
21899,22007.0,"[(22007, 1.0), (21469, 0.999385474623), (14406...",0.948388
21900,22008.0,"[(22008, 1.0), (700, 0.999297863344), (11250, ...",0.924647
21901,22009.0,"[(22009, 1.0), (19219, 0.999669006142), (17596...",0.968913
21902,22010.0,"[(22010, 1.0), (11742, 0.999496523293), (8272,...",0.920009
21903,22011.0,"[(22016, 1.0), (22011, 1.0), (22015, 1.0), (22...",0.959647
21904,22012.0,"[(22016, 1.0), (22011, 1.0), (22015, 1.0), (22...",0.959647
21905,22013.0,"[(22013, 1.0), (22019, 1.0), (22021, 1.0), (22...",0.959647
21906,22014.0,"[(22016, 1.0), (22011, 1.0), (22015, 1.0), (22...",0.959647
21907,22015.0,"[(22016, 1.0), (22011, 1.0), (22015, 1.0), (22...",0.959647
21908,22016.0,"[(22016, 1.0), (22011, 1.0), (22015, 1.0), (22...",0.959647
21909,22017.0,"[(22016, 1.0), (22011, 1.0), (22015, 1.0), (22...",0.959647
21910,22018.0,"[(22016, 1.0), (22011, 1.0), (22015, 1.0), (22...",0.959647
21911,22019.0,"[(22013, 1.0), (22019, 1.0), (22021, 1.0), (22...",0.959647
21912,22020.0,"[(22016, 1.0), (22011, 1.0), (22015, 1.0), (22...",0.959647
21913,22021.0,"[(22013, 1.0), (22019, 1.0), (22021, 1.0), (22...",0.959647
21914,22022.0,"[(22013, 1.0), (22019, 1.0), (22021, 1.0), (22...",0.959647
21915,22023.0,"[(22013, 1.0), (22019, 1.0), (22021, 1.0), (22...",0.959647
21916,22024.0,"[(22024, 1.0), (2046, 0.999303750189), (7999, ...",0.955703
21917,22025.0,"[(22025, 1.0), (21005, 0.999645621297), (15319...",0.933733
21918,22026.0,"[(15321, 1.0), (18248, 1.0), (21006, 1.0), (22...",0.933755
21919,22027.0,"[(22027, 1.0), (18536, 0.999130337667), (21663...",0.961478
21920,22028.0,"[(22028, 1.0), (18260, 0.999869055996), (7490,...",0.956378
21921,22029.0,"[(22029, 1.0), (17745, 0.999027751883), (435, ...",0.970130
21922,22030.0,"[(22030, 1.0), (7890, 0.999393673854), (19111,...",0.967490
21923,22031.0,"[(22031, 1.0), (2269, 0.999314585385), (9896, ...",0.968039
21924,22032.0,"[(22032, 1.0), (14297, 0.99929372874), (20673,...",0.948093
21925,22033.0,"[(22033, 1.0), (15144, 0.999297717747), (10374...",0.952318
21926,22034.0,"[(22034, 1.0), (15839, 0.999440199305), (12089...",0.957718
21927,22035.0,"[(22035, 1.0), (11435, 0.999507281561), (12009...",0.886610

In [373]:
items_data[items_data['pid'] == 2]

,pid,manufacturer,group,content,unit,pharmForm,genericProduct,salesIndex,category,campaignIndex,rrp
1,2,1,2FOI,80,ST,Tab,0,40,NaN,NaN,10.89

In [374]:
items_data[items_data['pid'] == 15003]

,pid,manufacturer,group,content,unit,pharmForm,genericProduct,salesIndex,category,campaignIndex,rrp
15002,15003,1,2FOI,80,ST,Tab,0,40,NaN,NaN,10.89

In [377]:
items_data[items_data['pid'] == 14831]

,pid,manufacturer,group,content,unit,pharmForm,genericProduct,salesIndex,category,campaignIndex,rrp
14830,14831,1,2FOI,80,ST,Tab,0,40,NaN,NaN,10.89

In [378]:
items_data[items_data['pid'] == 6341]

,pid,manufacturer,group,content,unit,pharmForm,genericProduct,salesIndex,category,campaignIndex,rrp
6340,6341,1,2FOI,80,ST,Tab,0,40,NaN,NaN,10.89

In [379]:
training_similarities_df['avg_similarity'].mean()

0.9430376195142414

In [387]:
training_similarities_df.to_csv('./train_similarities.csv', sep='|', index=False)

In [386]:
pd.DataFrame.to_csv??